'use client';

import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowLeft, ArrowRight, AudioLines, Check, ChevronRight, CircleHelp, Clock3, Cpu, Download, FlaskConical, Hand, Link2, LoaderCircle, Pause, Play, Radio, RefreshCw, RotateCcw, Settings2, Shuffle, SkipForward, Upload, Waves, Zap } from 'lucide-react';
import { Line, LineChart, CartesianGrid, XAxis, YAxis, ReferenceLine } from 'recharts';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart';
import { NetworkView } from './network-view';
import { ARCHITECTURES } from '@/lib/jev';
import { summarize } from '@/lib/metrics';
import { PendulumStage } from './pendulum-stage';
import { DEFAULT_CONFIG, Experiment, parseRecording, type Config, type Controller } from '@/lib/experiment';
import { degrees, parameters } from '@/lib/physics';

const controllerInfo: Record<Controller, { label: string; subtitle: string; icon: typeof Cpu }> = {
  jev: { label: 'Jev AI', subtitle: 'TypeSafe Choice', icon: Cpu }, manual: { label: '직접 조작', subtitle: '방향키 / 터치', icon: Hand }, random: { label: '무작위', subtitle: '시드 고정', icon: Shuffle },
};
const fixed = (n: number, places = 2) => Number.isFinite(n) ? n.toFixed(places) : '—';

export default function Lab() {
  const [engine] = useState(() => new Experiment());
  const [, render] = useState(0);
  const [config, setConfig] = useState<Config>({ ...DEFAULT_CONFIG });
  const [connection, setConnection] = useState<{ configured: boolean; model: string } | null>(null);
  const [settings, setSettings] = useState(false), [help, setHelp] = useState(false), [connect, setConnect] = useState(false);
  const [notice, setNotice] = useState(''), [connecting, setConnecting] = useState(false);
  const upload = useRef<HTMLInputElement>(null);
  const [comparisons, setComparisons] = useState<ReturnType<typeof summarize>[]>([]);
  const archived = useRef(new WeakSet<object>());
  const archive = () => { if (!engine.replay && engine.frames.length > 1 && !archived.current.has(engine.frames)) { archived.current.add(engine.frames); setComparisons(previous => [...previous.slice(-19), summarize(engine.export())]); } };
  useEffect(() => { if (engine.reason) archive(); }, [engine.reason]);
  const [logTab, setLogTab] = useState('telemetry');
  const [draft, setDraft] = useState(config);
  const refreshConnection = async () => { setConnecting(true); try { const r = await fetch('/api/jev'); if (!r.ok) throw new Error(); setConnection(await r.json()); } catch { setConnection(null); setNotice('연결 상태를 확인하지 못했습니다. 잠시 후 다시 시도하세요.'); } finally { setConnecting(false); } };
  useEffect(() => {
    const off = engine.subscribe(() => render(v => v + 1));
    void refreshConnection();
    const visibility = () => { if (document.hidden) { engine.manual = 0; if (engine.running) { engine.pause(); setNotice('다른 화면으로 이동해 실험을 일시정지했습니다.'); } } };
    const blur = () => { engine.manual = 0; };
    const down = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLElement && (e.target.closest('input,select,textarea,[role="dialog"],button') || e.target.isContentEditable)) return;
      if (e.code === 'Space') { e.preventDefault(); if (engine.running) engine.pause(); else engine.start(); }
      if (engine.config.controller === 'manual' && (e.key === 'ArrowLeft' || e.key === 'ArrowRight')) { e.preventDefault(); engine.manual = e.key === 'ArrowLeft' ? -1 : 1; }
    };
    const up = (e: KeyboardEvent) => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') engine.manual = 0; };
    document.addEventListener('visibilitychange', visibility); window.addEventListener('blur', blur); window.addEventListener('keydown', down); window.addEventListener('keyup', up);
    return () => { off(); engine.dispose(); document.removeEventListener('visibilitychange', visibility); window.removeEventListener('blur', blur); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); };
  }, [engine]);
  useEffect(() => {
    type Tool = { name: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute(input: unknown): unknown };
    const context = (document as Document & { modelContext?: { registerTool(tool: Tool, options: { signal: AbortSignal }): void | Promise<void> } }).modelContext;
    if (!context) return;
    const lifecycle = new AbortController();
    const tools: Tool[] = [
      { name: 'read_pendulum_state', description: 'Read current simulation configuration, physical state, clocks and latest applied decision.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: () => ({ config: engine.config, state: engine.state, time: engine.time, wall: engine.wall, running: engine.running, decision: engine.decisions.at(-1) ?? null }) },
      { name: 'pause_pendulum_experiment', description: 'Pause the simulation and cancel any pending decision; preserves recorded data.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: (input) => { if (!input || typeof input !== 'object' || Object.keys(input).length) throw new Error('Expected empty object'); engine.pause(); return { running: false, time: engine.time }; } },
    ];
    tools.forEach(tool => { try { void Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => {}); } catch { /* Optional browser capability. */ } });
    return () => lifecycle.abort();
  }, [engine]);

  const change = (patch: Partial<Config>) => { archive(); const next = { ...config, ...patch }; engine.reset(next); setConfig(next); setNotice(''); };
  const p = parameters(config.topology), n = p.lengths.length + 1;
  const decisions = engine.replay ? engine.decisions.filter(d => d.appliedAt <= engine.time + 1e-9) : engine.decisions;
  const decision = decisions.at(-1);
  const totalCalls = decisions.reduce((sum, d) => sum + (d.calls || 0), 0);
  const inputTokens = decisions.every(d => d.inputTokens != null) ? decisions.reduce((sum, d) => sum + (d.inputTokens || 0), 0) : null;
  const frames = engine.replay ? engine.frames.slice(0, engine.replayIndex + 1) : engine.frames;
  const chart = frames.filter((_, i) => i % 4 === 0).map(f => ({ time: f.time, angle1: degrees(f.state[1]), angle2: config.topology === 'double' ? degrees(f.state[2]) : undefined }));
  const readOnly = engine.running || engine.pending || !!engine.replay;
  const unavailable = config.controller === 'jev' && !connection?.configured;
  const info = controllerInfo[config.controller];
  const start = () => { if (unavailable) { setConnect(true); return; } if (engine.running) engine.pause(); else engine.start(); };
  const save = () => {
    const blob = new Blob([JSON.stringify(engine.export())], { type: 'application/json' });
    const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = `pendulum-${config.topology}-${config.controller}-${Date.now()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice('상태와 판단 기록을 JSON으로 저장했습니다.');
  };
  const load = async (file: File | undefined) => {
    if (!file) return; engine.pause(); archive();
    try { if (file.size > 15000000) throw new Error('15MB 이하의 파일을 선택하세요.'); const recording = parseRecording(await file.text()); engine.load(recording); setConfig(recording.config); setNotice('저장된 움직임을 재생합니다. Jev API는 호출하지 않습니다.'); } catch (e) { setNotice(e instanceof Error ? e.message : '기록을 읽지 못했습니다.'); }
    if (upload.current) upload.current.value = '';
  };

  return <main className="lab-shell">
    <header className="topbar"><a className="wordmark" href="/"><Activity /><span>PENDULUM<span className="brand-light"> / LAB</span></span></a><span className="topbar-note">작은 움직임, 지능의 균형.</span><div className="header-actions"><span className="version-tag">EXPERIMENT 001</span><Button variant="ghost" size="icon" aria-label="실험 안내" onClick={() => setHelp(true)}><CircleHelp /></Button></div></header>
    <section className="page-heading"><div><div className="eyebrow">CONTROL INTELLIGENCE LAB</div><h1>균형을 만드는 판단.</h1><p>물리는 환경이, 균형은 Jev가. 보정 없는 역진자 제어 실험.</p></div><div className="heading-actions"><Button variant="outline" onClick={() => { engine.pause(); setConnect(true); }}><span className={`connection-dot ${connection?.configured ? 'connected' : ''}`} />{connection?.configured ? 'Jev 키 설정됨' : 'Jev 연결'}</Button><Button variant="outline" onClick={() => { engine.pause(); setDraft(config); setSettings(true); }}><Settings2 /> 실험 설정</Button></div></section>
    {(notice || engine.error) && <div className={`notice ${engine.error ? 'error' : ''}`} role="status"><span>{engine.error || notice}</span><Button variant="ghost" size="xs" onClick={() => { setNotice(''); engine.error = ''; render(v => v + 1); }}>닫기</Button></div>}
    <div className="lab-grid">
      <div className="left-column">
        <section className="panel simulation-panel">
          <div className="panel-heading"><div><span className="section-number">01</span><h2>물리 실험실</h2></div><span className={`status-pill ${engine.running ? 'live' : ''}`}><i />{engine.replay ? '기록 재생' : engine.pending ? '판단 대기' : engine.running ? '실험 중' : engine.reason ? '실험 종료' : engine.time > 0 ? '일시정지' : '준비'}</span></div>
          <div className="experiment-toolbar"><div className="segmented" role="group" aria-label="막대 구조 선택"><Button variant="ghost" disabled={readOnly} aria-pressed={config.topology === 'single'} className={config.topology === 'single' ? 'selected' : ''} onClick={() => change({ topology: 'single' })}><span className="rod-icon">╱</span> 단일 막대 <small>마디 0</small></Button><Button variant="ghost" disabled={readOnly} aria-pressed={config.topology === 'double'} className={config.topology === 'double' ? 'selected' : ''} onClick={() => change({ topology: 'double' })}><Link2/> 이중 막대 <small>마디 1</small></Button></div><label className="compact-select"><span className="sr-only">실험 목표</span><select disabled={readOnly} value={config.task} onChange={e => change({ task: e.target.value as Config['task'] })}><option value="balance">균형 유지</option><option value="swingup">아래에서 세우기</option></select></label></div>
          <div className="stage"><div className="stage-caption"><span><span className="tiny-dot" />{config.topology === 'single' ? 'SINGLE' : 'DOUBLE'} INVERTED PENDULUM</span><span>SI UNITS · 50 Hz</span></div><PendulumStage engine={engine}/>{engine.reason && <div className="stage-result"><span className="eyebrow">EXPERIMENT COMPLETE</span><h3>{engine.reason}</h3><p>가상 {fixed(engine.time)}초 · 최장 균형 {fixed(engine.bestBalance)}초</p><Button variant="outline" onClick={() => { archive(); engine.reset(); }}><RotateCcw/> 같은 조건으로 다시</Button></div>}</div>
          <div className="transport"><div className="transport-buttons"><Button className="start-button" disabled={!!engine.reason || (engine.pending && !engine.running)} onClick={start}>{engine.running ? <Pause/> : <Play/>}{engine.running ? '일시정지' : engine.replay ? '기록 재생' : engine.time > 0 ? '실험 재개' : '실험 시작'}</Button><Button variant="outline" disabled={engine.running || engine.pending || !!engine.reason || unavailable} onClick={() => void engine.singleStep()} title="가상 시간 20ms 한 스텝"><SkipForward/><span className="step-label">한 스텝</span></Button><Button variant="ghost" size="icon" aria-label="실험 초기화" title="현재 설정으로 초기화" onClick={() => { archive(); engine.reset(); }}><RotateCcw/></Button></div><span className="keyboard-hint"><kbd>SPACE</kbd> 시작 / 정지</span></div>
          <div className="metrics"><Metric label="가상 시간" value={fixed(engine.time)} unit="s"/><Metric label="실제 경과" value={fixed(engine.wall, 1)} unit="s"/><Metric label="연속 균형" value={fixed(engine.balance, 1)} unit="s"/><Metric label="판단 횟수" value={String(decisions.length).padStart(3, '0')} unit="회"/></div>
        </section>
        <section className="panel controller-panel"><div className="control-header"><h2>제어 주체를 선택하세요</h2><span>{engine.replay ? '저장된 실험' : '제어기 선택'}</span></div><div className="controller-options">{Object.entries(controllerInfo).map(([id, item]) => <Button key={id} variant="ghost" className={`controller-card ${config.controller === id ? 'active' : ''}`} disabled={readOnly} aria-pressed={config.controller === id} onClick={() => change({ controller: id as Controller })}><item.icon/><div><strong>{item.label}</strong><small>{item.subtitle}</small></div>{config.controller === id && <Check className="controller-check"/>}</Button>)}</div><div className="clock-options"><div className="clock-label"><Clock3/><span>시간 진행</span></div><div className="radio-options"><label><input disabled={readOnly} type="radio" name="clock" checked={config.clock === 'wait'} onChange={() => change({ clock: 'wait' })}/>판단 대기형 <small>응답 후 20 ms</small></label><label><input disabled={readOnly} type="radio" name="clock" checked={config.clock === 'realtime'} onChange={() => change({ clock: 'realtime' })}/>실시간형 <small>이전 힘 유지</small></label></div></div><div className="mode-note"><span className="note-dot"/>{config.clock === 'wait' ? '응답을 기다리는 동안 물리 시간이 멈춥니다. 판단 자체를 비교하세요.' : '응답을 기다려도 물리 시간이 흐릅니다. 통신 지연의 영향을 관찰하세요.'}</div>
          {config.controller === 'manual' && <div className="manual-controls">{[-1, 1].map(dir => <Button key={dir} variant="outline" disabled={!!engine.replay || !!engine.reason} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); engine.manual = dir; }} onPointerUp={() => { engine.manual = 0; }} onPointerCancel={() => { engine.manual = 0; }} onLostPointerCapture={() => { engine.manual = 0; }} onKeyDown={e => { if (e.code === 'Space' || e.code === 'Enter') engine.manual = dir; }} onKeyUp={() => { engine.manual = 0; }}>{dir < 0 ? <ArrowLeft/> : <ArrowRight/>}{dir < 0 ? '왼쪽으로 밀기' : '오른쪽으로 밀기'}</Button>)}<small>누르는 동안 힘이 적용됩니다.</small></div>}
          <div className="disturb-row"><span><Waves/> 외란 테스트</span><Button variant="outline" size="sm" disabled={!!engine.replay || !!engine.reason || (engine.pending && config.clock === 'wait')} onClick={() => engine.disturb('pole')}>막대 건드리기 <Zap/></Button><Button variant="ghost" size="sm" disabled={!!engine.replay || !!engine.reason || (engine.pending && config.clock === 'wait')} onClick={() => engine.disturb('cart')}>수레 밀기 <ArrowRight/></Button></div>
        </section>
      </div>
      <aside className="panel insight-panel"><div className="panel-heading"><div><span className="section-number">02</span><h2>판단 인사이트</h2></div><AudioLines size={17} className="subtle-icon"/></div><div className="insight-source"><div className="engine-icon"><info.icon/></div><div><strong>{info.label}</strong><span>{config.controller === 'jev' ? decision?.model || connection?.model || 'jev-latest' : info.subtitle}</span></div><span className="small-tag">{config.controller === 'jev' ? decision ? 'API LIVE' : '미실행' : 'LOCAL'}</span></div>
        <div className="insight-step"><div className="step-title"><span>1</span><h3>현재 상태를 읽고</h3><small>OBSERVE</small></div><div className="state-grid"><StateValue symbol="x" label="수레 위치" value={fixed(engine.state[0])} unit="m"/><StateValue symbol="v" label="수레 속도" value={fixed(engine.state[n])} unit="m/s"/>{p.lengths.map((_, i) => <StateValue key={i} symbol={`θ${i + 1}`} label={`막대 ${i + 1} 각도`} value={fixed(degrees(engine.state[i + 1]), 1)} unit="°"/>)}{p.lengths.map((_, i) => <StateValue key={i} symbol={`ω${i + 1}`} label={`막대 ${i + 1} 각속도`} value={fixed(engine.state[n + i + 1])} unit="rad/s"/>)}</div><p className="micro-copy">각도는 위쪽 수직 0° 기준 · + 방향은 오른쪽</p></div>
        <div className="flow-arrow"><ArrowDown size={14}/></div>
        <div className="insight-step"><div className="step-title"><span>2</span><h3>{config.controller === 'jev' ? '다음 방향을 선택해' : '다음 힘을 계산해'}</h3><small>DECIDE</small></div>{config.controller === 'jev' ? <><Probability label="LEFT" value={decision?.probabilities?.LEFT} active={decision?.action === 'LEFT'}/><Probability label="RIGHT" value={decision?.probabilities?.RIGHT} active={decision?.action === 'RIGHT'}/><div className="confidence-row"><span>모델 confidence</span><strong>{decision?.confidence == null ? '—' : fixed(decision.confidence, 3)}</strong></div><p className="micro-copy">API가 반환한 선택 분포입니다. 성공률이나 내부 사고 과정을 뜻하지 않습니다.</p></> : <div className="calculation"><div className="formula">{config.controller === 'random' ? 'F ∈ { −Fmax, +Fmax }' : 'F = input × Fmax'}</div><p>{config.controller === 'random' ? `시드 ${config.seed}의 무작위 힘` : '방향키 또는 화면 버튼의 힘만 적용합니다.'}</p><p className="micro-copy">물리 확인용 · 자동 균형 보정 없음</p></div>}</div>
        <div className="flow-arrow"><ArrowDown size={14}/></div>
        <div className="insight-step action-step"><div className="step-title"><span>3</span><h3>수레에 힘을 전달합니다</h3><small>ACT</small></div><div className="action-result"><div className="direction-icon">{engine.pending && config.clock === 'wait' ? <LoaderCircle className="spin"/> : engine.force > .001 ? <ArrowRight/> : engine.force < -.001 ? <ArrowLeft/> : <Pause/>}</div><div><strong>{engine.pending && config.clock === 'wait' ? '응답 대기' : decision?.action === 'RIGHT' ? '오른쪽으로' : decision?.action === 'LEFT' ? '왼쪽으로' : '입력 대기'}</strong><span>F = {fixed(engine.force)} N</span></div></div><div className="latency-row"><span><Radio/> 최근 응답</span><strong>{decision ? `${fixed(decision.latency, 0)} ms` : '—'}</strong></div><div className="latency-row"><span>관측 → 적용 (가상)</span><strong>{decision ? `${fixed((decision.appliedAt - decision.observedAt) * 1000, 0)} ms` : '—'}</strong></div></div>
        <div className="insight-footer"><FlaskConical size={15}/><p>{config.controller === 'jev' ? '오류가 발생하면 일시정지합니다. 다른 제어기로 자동 전환하지 않습니다.' : '물리 엔진은 주어진 힘만 적분합니다. 막대를 세우거나 균형을 보정하지 않습니다.'}</p></div>
      </aside>
    </div>
    <NetworkView architecture={config.architecture} onChange={architecture => change({ architecture })} disabled={readOnly || config.controller !== 'jev'} layers={config.controller === 'jev' ? decision?.layers : undefined} pending={engine.pending} observedAt={config.controller === 'jev' ? decision?.observedAt : undefined} calls={totalCalls} inputTokens={inputTokens}/>
    <section className="panel records-panel"><Tabs value={logTab} onValueChange={value => setLogTab(String(value))}><div className="records-heading"><div><span className="section-number">04</span><TabsList variant="line"><TabsTrigger value="telemetry"><Activity/> 움직임 기록</TabsTrigger><TabsTrigger value="decisions"><Cpu/> 판단 로그 <span className="count-badge">{decisions.length}</span></TabsTrigger><TabsTrigger value="input">입력 데이터</TabsTrigger><TabsTrigger value="compare">실험 비교</TabsTrigger></TabsList></div><div className="record-actions"><Button variant="ghost" size="sm" onClick={() => upload.current?.click()}><Upload/> 불러오기</Button><Button variant="outline" size="sm" disabled={engine.frames.length < 2} onClick={save}><Download/> 기록 저장</Button><input ref={upload} type="file" accept="application/json,.json" className="sr-only" onChange={e => void load(e.target.files?.[0])}/></div></div>
      <TabsContent value="telemetry"><div className="chart-header"><div><strong>수직으로부터의 각도</strong><span>목표 범위 ±12°</span></div><div className="chart-legend"><i/> 막대 1 {config.topology === 'double' && <><i className="second"/> 막대 2</>}</div></div><ChartContainer config={{ angle1: { label: '막대 1 (°)', color: '#658951' }, angle2: { label: '막대 2 (°)', color: '#bd9c5f' } }} className="telemetry-chart"><LineChart data={chart} margin={{ top: 4, right: 20, left: -10, bottom: 5 }}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="time" type="number" domain={[0, Math.max(10, Math.ceil(engine.time / 10) * 10)]} tickFormatter={v => `${v}s`} tickLine={false} axisLine={false} minTickGap={35}/><YAxis domain={config.task === 'balance' ? [-15, 15] : [-180, 180]} tickLine={false} axisLine={false} tickFormatter={v => `${v}°`} width={56}/><ReferenceLine y={0} stroke="#adbba0"/><ReferenceLine y={12} stroke="#d8dfd0" strokeDasharray="5 5"/><ReferenceLine y={-12} stroke="#d8dfd0" strokeDasharray="5 5"/><ChartTooltip content={<ChartTooltipContent/>}/><Line dataKey="angle1" type="linear" stroke="var(--color-angle1)" strokeWidth={2} dot={false} isAnimationActive={false}/>{config.topology === 'double' && <Line dataKey="angle2" type="linear" stroke="var(--color-angle2)" strokeWidth={1.8} dot={false} isAnimationActive={false}/>}</LineChart></ChartContainer>{engine.frames.length === 1 && <p className="chart-empty">실험을 시작하면 각도 변화가 여기에 쌓입니다.</p>}</TabsContent>
      <TabsContent value="decisions"><div className="table-wrap"><table className="decision-table"><thead><tr><th>STEP</th><th>관측 → 적용</th><th>선택</th><th>힘</th><th>P(RIGHT)</th><th>응답 시간</th><th>제어기 / 모델</th></tr></thead><tbody>{decisions.slice(-100).reverse().map(d => <tr key={d.id}><td>#{String(d.id).padStart(4, '0')}</td><td>{fixed(d.observedAt)} → {fixed(d.appliedAt)} s</td><td className="table-action">{d.action === 'RIGHT' ? '→' : d.action === 'LEFT' ? '←' : '–'} {d.action}</td><td>{fixed(d.force)} N</td><td>{d.probabilities ? `${fixed(d.probabilities.RIGHT * 100, 1)}%` : '—'}</td><td>{fixed(d.latency, 0)} ms</td><td>{d.model}</td></tr>)}</tbody></table>{!decisions.length && <div className="empty-log"><Cpu/><p>첫 판단을 기다리고 있습니다.</p><span>실험을 시작하거나 ‘한 스텝’을 눌러 보세요.</span></div>}</div><p className="table-note">최근 100개 표시 · 전체 판단과 상태는 기록 저장에 포함됩니다.</p></TabsContent>
      <TabsContent value="input"><div className="input-preview"><p>선택한 네트워크의 첫 층에 전달될 상태와 질문입니다. 다음 층에는 앞선 Jev의 실제 판단이 추가됩니다. 관측 설명에는 권장 행동·미래 예측·보조 제어 계산을 넣지 않습니다.</p><pre>{JSON.stringify(engine.inputPreview(), null, 2)}</pre></div></TabsContent>
      <TabsContent value="compare"><div className="comparison-intro"><strong>같은 조건에서 네트워크를 바꿔 보세요.</strong><p>종료하거나 초기화한 최근 20회 실험을 이 탭에서 비교합니다. ‘성공’은 모든 막대가 ±12°·각속도 1 rad/s 이내를 2초 연속 유지한 경우입니다.</p><span>시드뿐 아니라 막대 구조·목표·힘·시간 모드·추가 지연도 같아야 비교가 가능합니다. 여기의 결과는 표본별 기록이며 통계적 우위를 의미하지 않습니다.</span></div><div className="table-wrap"><table className="decision-table"><thead><tr><th>구성 / 조건</th><th>가상 시간</th><th>최장 균형</th><th>2초 성공</th><th>최대 각도</th><th>수레 이동</th><th>행동 전환</th><th>API 호출</th><th>입력 tokens</th><th>평균 응답</th></tr></thead><tbody>{comparisons.map((run, i) => <tr key={i}><td>{run.config.controller === 'jev' ? ARCHITECTURES[run.config.architecture].label : controllerInfo[run.config.controller].label}<small className="comparison-condition">{run.config.topology} · {run.config.task} · seed {run.config.seed}<br/>{run.config.force}N · {run.config.clock} · +{run.config.delay}ms · {run.config.duration}s · {run.config.representation}</small></td><td>{fixed(run.elapsed)} s</td><td>{fixed(run.bestBalance)} s</td><td>{run.success ? '성공' : '미달성'}</td><td>{fixed(run.maxAngle, 1)}°</td><td>{fixed(run.travel)} m</td><td>{run.switches}</td><td>{run.calls}</td><td>{run.inputTokens ?? '—'}</td><td>{fixed(run.meanLatency, 0)} ms</td></tr>)}</tbody></table>{!comparisons.length && <div className="empty-log"><FlaskConical/><p>비교할 실험이 아직 없습니다.</p><span>실험 후 초기화하거나 종료하면 결과가 쌓입니다.</span></div>}</div><p className="table-note">비교 목록은 현재 페이지 세션에만 유지됩니다. 개별 실험은 JSON으로 저장하세요. 호출·토큰은 완료된 스텝만 집계합니다. 실패·취소 과금은 TypeSafe 사용 내역에서 확인하세요.</p></TabsContent>
    </Tabs>{engine.replay && <div className="replay-bar"><span>REPLAY</span><input aria-label="기록 재생 위치" type="range" min={0} max={engine.frames.length - 1} value={engine.replayIndex} onChange={e => engine.seek(Number(e.target.value))}/><span>{fixed(engine.time)} s</span><Button variant="ghost" size="sm" onClick={() => { archive(); engine.reset(); }}>재생 종료</Button></div>}</section>
    <footer className="footer"><span><span className="tiny-dot"/> PHYSICS FIRST. INTELLIGENCE IN MOTION.</span><span>질점 모델 · RK4 적분 · 관측과 제어를 분리한 실험</span><Button variant="link" size="sm" onClick={() => setHelp(true)}>실험 안내 <ChevronRight/></Button></footer>

    <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="lab-dialog"><DialogHeader><DialogTitle>실험 설정</DialogTitle><DialogDescription>설정을 적용하면 같은 시드의 초기 상태에서 새 실험을 시작합니다.</DialogDescription></DialogHeader><div className="settings-grid"><label>최대 힘 <span>{draft.force} N</span><input type="range" min={2} max={20} step={1} value={draft.force} onChange={e => setDraft({ ...draft, force: Number(e.target.value) })}/></label><label>추가 응답 지연 <span>{draft.delay} ms</span><input type="range" min={0} max={1000} step={50} value={draft.delay} onChange={e => setDraft({ ...draft, delay: Number(e.target.value) })}/></label><label>실험 시간<select value={draft.duration} onChange={e => setDraft({ ...draft, duration: Number(e.target.value) })}><option value={10}>10초</option><option value={30}>30초</option><option value={60}>60초</option><option value={120}>120초</option></select></label><label>초기 조건 시드<Input type="number" min={0} max={999999} value={draft.seed} onChange={e => setDraft({ ...draft, seed: Math.max(0, Math.min(999999, Math.floor(Number(e.target.value)) || 0)) })}/></label><label className="full-width">Jev 입력 표현<select value={draft.representation} onChange={e => setDraft({ ...draft, representation: e.target.value as Config['representation'] })}><option value="described">수치 + 상태 설명</option><option value="numeric">수치만</option></select></label></div><div className="setting-explainer"><strong>물리 조건</strong><p>수레 1 kg · 중력 9.81 m/s² · 레일 ±2.4 m<br/>단일: 1.5 m / 0.2 kg<br/>이중: 0.85 + 0.75 m / 0.15 + 0.12 kg</p></div><Button onClick={() => { change(draft); setSettings(false); }}>설정 적용 · 새 실험</Button></DialogContent></Dialog>
    <Dialog open={connect} onOpenChange={setConnect}><DialogContent className="lab-dialog"><DialogHeader><div className="modal-icon"><Cpu/></div><DialogTitle>Jev 엔진 연결</DialogTitle><DialogDescription>수치 상태를 TypeSafe에 전달하고 실제 선택 확률을 받아옵니다.</DialogDescription></DialogHeader><div className="connection-state"><span className={`connection-dot ${connection?.configured ? 'connected' : ''}`}/><strong>{connection?.configured ? '서버에 API 키가 설정되어 있습니다' : '서버에 API 키를 설정해 주세요'}</strong></div><p className="dialog-copy">프로젝트의 <code>.env</code>에 아래 값을 입력하고 앱을 다시 실행하세요. 호스팅에서는 같은 이름의 비밀 환경 변수로 설정합니다.</p><pre className="env-example">TYPESAFE_API_KEY=발급받은_키<br/>JEV_MODEL=jev-latest</pre><p className="dialog-copy">키는 서버에만 보관합니다. 키가 없을 때는 수동·무작위로 물리 움직임을 확인할 수 있습니다. Jev 결과를 모사하지 않습니다.</p><a className="external-link" href="https://console.typesafe.ai/" target="_blank" rel="noreferrer">TypeSafe에서 API 키 발급 <ArrowRight size={15}/></a><div className="setting-explainer">Jev는 LEFT 또는 RIGHT만 적용합니다. 단일 구성은 최대 초당 10스텝, 다층은 5스텝으로 제한합니다. 같은 층의 질문을 묶어 보내며, 서비스 오류 시 실험을 멈춥니다. 실제 연결 검증은 첫 실험 요청에서 이뤄집니다.</div><Button disabled={connecting} onClick={() => void refreshConnection()}>{connecting ? <LoaderCircle className="spin"/> : <RefreshCw/>} 연결 상태 새로고침</Button></DialogContent></Dialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="lab-dialog guide-dialog"><DialogHeader><DialogTitle>작은 힘으로, 불안정한 균형을.</DialogTitle><DialogDescription>같은 물리 환경에서 서로 다른 제어 방식을 비교하는 실험실입니다.</DialogDescription></DialogHeader><div className="guide-content"><h3>두 가지 구조와 목표</h3><p>단일 막대는 중간 마디가 없고, 이중 막대는 자유롭게 도는 관절이 하나 있습니다. 균형 유지는 거의 선 상태에서 시작하고 ±12°를 넘으면 종료합니다. 아래에서 세우기는 매달린 상태에서 시작하며, 레일 이탈 또는 제한 시간에 종료합니다.</p><h3>판단과 속도를 나누어 관찰하세요</h3><p>판단 대기형은 응답 후 20 ms씩 진행합니다. 실제 경과 시간과 가상 시간이 다를 수 있습니다. 실시간형은 기다리는 동안 이전 힘을 유지합니다. 탭을 벗어나면 실험은 일시정지됩니다.</p><h3>인사이트를 읽는 방법</h3><p>Jev의 입력 상태, 반환 확률과 confidence, 적용 결과를 보여줍니다. 내부 추론은 제공하지 않습니다. 물리 엔진은 Jev가 선택한 힘만 적용합니다. 자동 균형 제어·행동 추천·숨은 보정은 없습니다. 수동·무작위는 물리 동작 확인을 위한 별도 모드입니다.</p><h3>실험의 범위</h3><p>막대는 질량이 없는 강체 링크, 끝점은 질점으로 모델링했습니다. 다층 구성의 모든 중간 노드도 실제 Jev 요청입니다. 순환 구성은 이전 3스텝을 입력으로 돌려주며 학습을 수행하지 않습니다. Jev의 성능은 실제 실행으로 측정해야 합니다.</p><div className="guide-links"><a href="https://docs.typesafe.ai/api" target="_blank" rel="noreferrer">Jev API 문서 ↗</a><a href="https://underactuated.mit.edu/acrobot.html" target="_blank" rel="noreferrer">물리 모델 참고 ↗</a></div></div></DialogContent></Dialog>
  </main>;
}

function Metric({ label, value, unit }: { label: string; value: string; unit: string }) { return <div className="metric"><span>{label}</span><div>{value}<small>{unit}</small></div></div>; }
function StateValue({ symbol, label, value, unit }: { symbol: string; label: string; value: string; unit: string }) { return <div className="state-value"><div><span>{symbol}</span><small>{label}</small></div><strong>{value}<em>{unit}</em></strong></div>; }
function Probability({ label, value, active }: { label: string; value?: number; active: boolean }) { return <div className={`probability ${active ? 'active' : ''}`}><div><span>{label === 'LEFT' ? '←' : '→'} {label}</span><strong>{value == null ? '—' : `${(value * 100).toFixed(1)}%`}</strong></div><div className="probability-track"><span style={{ width: `${(value ?? 0) * 100}%` }}/></div></div>; }
